# Generated by Django 4.0.4 on 2022-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='bilans_bramkowy',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='liga',
            name='ilosc_klubow',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='liga',
            name='ilosc_punktow',
            field=models.CharField(max_length=30),
        ),
    ]
