# Generated by Django 4.0.4 on 2022-06-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_liga_bilans_bramkowy_alter_liga_ilosc_klubow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('wiek', models.CharField(max_length=3)),
                ('poprzednie_kluby', models.CharField(max_length=100)),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.klub')),
            ],
        ),
        migrations.CreateModel(
            name='Pilkarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('poprzednie_kluby', models.CharField(max_length=100)),
                ('numer_koszulki', models.CharField(max_length=3)),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.klub')),
            ],
        ),
    ]
