# Generated by Django 4.0.4 on 2022-06-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_sedzia_trener_pilkarz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=20)),
                ('ulica', models.CharField(max_length=20)),
                ('numer_ulicy', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('ilosc_miejsc', models.CharField(max_length=8)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.adres')),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.klub')),
            ],
        ),
    ]
