# Generated by Django 4.0.4 on 2022-06-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_rename_menadzer_klub_prezes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='kluby',
        ),
    ]
