# Generated by Django 4.0.4 on 2022-06-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_remove_liga_kluby'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.liga'),
        ),
    ]
