# Generated by Django 4.0.4 on 2022-06-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_klub_liga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liga',
            name='bilans_bramkowy',
        ),
        migrations.RemoveField(
            model_name='liga',
            name='ilosc_punktow',
        ),
        migrations.AddField(
            model_name='liga',
            name='prezes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
