# Generated by Django 4.0.4 on 2022-06-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_remove_liga_bilans_bramkowy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecz',
            name='godzina_rozpoczecia',
            field=models.DateTimeField(),
        ),
    ]
