# Generated by Django 4.0.4 on 2022-06-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_mecz_godzina_rozpoczecia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='poprzednie_kluby',
        ),
    ]
