# Generated by Django 4.0.4 on 2022-06-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_remove_trener_poprzednie_kluby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilkarz',
            old_name='poprzednie_kluby',
            new_name='poprzedni_klub',
        ),
    ]
